### PR TITLE
chore: update to 0.12.4 + sync from snapshot

### PR DESCRIPTION
**Pull request by lgaroche**
1. Update to use the latest Juno version: 0.12.4
1. Add a startup script that fetches the lastest snapshot from Nethermind. Can ben skipped it needed.
1. Add a optional L1 configuration for verification

### CODE REVIEW

**Review by ArturVargas — APPROVED** [review]
LGTM, thanks for contributing

**Comment by palomato** [comment]
Screenshot 2024-11-30 152620

[https://dappnode.github.io/explorer/#/repo/0xe01a9f110bc3e17288784664f8b8d96b23ac21ff/0.1.0](https://dappnode.github.io/explorer/#/repo/0xe01a9f110bc3e17288784664f8b8d96b23ac21ff/0.1.0)

Not sure if this is the correct package ☝️ Is an update needed to push out @lgaroche's changes?

Sorry I'm not more knowledgeable on DappNode process for publishing packages, but I am interested to run 0.12.4.

**Comment by lgaroche** [comment]
How did you do it the first time? I believe that you have to send a tx with the updated hash using the dappnode sdk: https://docs.dappnode.io/docs/dev/sdk/sdk-publish

**Comment by ArturVargas** [comment]
Hi @palomato @lgaroche I make the publish transaction today, /ipfs/Qmdehpea2pyfgSL66ZzUJ5E5YLvnJBycNDbobKebaGJHT6
https://dappnode.github.io/explorer/#/repo/0xe01a9f110bc3e17288784664f8b8d96b23ac21ff

**Comment by palomato** [comment]
Screenshot 2024-12-02 182532

Tried installing in DAppNode but package manager errors stating there is no content. Think something might have occurred with the publish, because DAppNode Explorer shows filesizes are all under 1kb ☝️. Explains the error.

I don't want to cause more work, and the package will need updated periodically anyway with new Juno releases. So I will try running Juno outside DAppNode and do updates manually. Thank you anyway for trying to make it work on DAppNode!

**Comment by ArturVargas** [comment]
> Screenshot 2024-12-02 182532
> Tried installing in DAppNode but package manager errors stating there is no content. Think something might have occurred with the publish, because DAppNode Explorer shows filesizes are all under 1kb ☝️. Explains the error.
> 
> I don't want to cause more work, and the package will need updated periodically anyway with new Juno releases. So I will try running Juno outside DAppNode and do updates manually. Thank you anyway for trying to make it work on DAppNode!

I already re-deploy the image, could you try again please, https://dappnode.github.io/explorer/#/repo/0xe01a9f110bc3e17288784664f8b8d96b23ac21ff/1.0.0

**Comment by lgaroche** [comment]
Hi @ArturVargas , I see your package in DappNode, and I received an update notification. However, your bumped the package version to 1.0.0, is it on purpose? It doesn't match the version in the repo.

**Comment by ArturVargas** [comment]
Hi @lgaroche, I have to publish the package with the dappnode sdk as a major version to generate new files, the first time I publish as a minor version the files doesn’t work correctly, I fix the version on the repo, thanks

**Pull request merged**
